name: Kibtek Bakiye Scraper

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: # İstediğimiz zaman manuel çalıştırma butonu ekler

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Chrome Kurulumu
      uses: browser-actions/setup-chrome@latest

    - name: Kütüphaneleri Yükle
      run: |
        pip install -r requirements.txt


    - name: Botu Çalıştır
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python app.py
